#define NUM_TESTS_FIND_OBJECT 20
#define PRB_ERROR_FIND_OBJECT .20
//#define INTENTS_FIND_OBJECT NUM_TESTS_FIND_OBJECT*PRB_ERROR_FIND_OBJECT*2
#define INTENTS_FIND_OBJECT 4
#define EXE_TIME_FIND_OBJECT 1.0 
#define LIMIT_EXE_TIME_FIND_OBJECT EXE_TIME_FIND_OBJECT*2 
//#define LIMIT_EXE_TIME_FIND_OBJECT EXE_TIME_FIND_OBJECT+EXE_TIME_FIND_OBJECT/2 
//#define LIMIT_EXE_TIME_FIND_OBJECT EXE_TIME_FIND_OBJECT 
