// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExplorationInfo.proto

#include "ExplorationInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_ExplorationInfo_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ExplorationInfo_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ExplorationZone;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ExplorationInfo_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_ExplorationSignal;
}  // namespace protobuf_ExplorationInfo_2eproto
namespace protobuf_MachineInfo_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_MachineInfo_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_LightSpec;
}  // namespace protobuf_MachineInfo_2eproto
namespace llsf_msgs {
class ExplorationSignalDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ExplorationSignal>
      _instance;
} _ExplorationSignal_default_instance_;
class ExplorationZoneDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ExplorationZone>
      _instance;
} _ExplorationZone_default_instance_;
class ExplorationInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ExplorationInfo>
      _instance;
} _ExplorationInfo_default_instance_;
}  // namespace llsf_msgs
namespace protobuf_ExplorationInfo_2eproto {
static void InitDefaultsExplorationSignal() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::llsf_msgs::_ExplorationSignal_default_instance_;
    new (ptr) ::llsf_msgs::ExplorationSignal();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::llsf_msgs::ExplorationSignal::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ExplorationSignal =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsExplorationSignal}, {
      &protobuf_MachineInfo_2eproto::scc_info_LightSpec.base,}};

static void InitDefaultsExplorationZone() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::llsf_msgs::_ExplorationZone_default_instance_;
    new (ptr) ::llsf_msgs::ExplorationZone();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::llsf_msgs::ExplorationZone::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ExplorationZone =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsExplorationZone}, {}};

static void InitDefaultsExplorationInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::llsf_msgs::_ExplorationInfo_default_instance_;
    new (ptr) ::llsf_msgs::ExplorationInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::llsf_msgs::ExplorationInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_ExplorationInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsExplorationInfo}, {
      &protobuf_ExplorationInfo_2eproto::scc_info_ExplorationSignal.base,
      &protobuf_ExplorationInfo_2eproto::scc_info_ExplorationZone.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ExplorationSignal.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ExplorationZone.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ExplorationInfo.base);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationSignal, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationSignal, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationSignal, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationSignal, lights_),
  0,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationZone, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationZone, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationZone, zone_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationZone, team_color_),
  1,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationInfo, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationInfo, signals_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::ExplorationInfo, zones_),
  ~0u,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::llsf_msgs::ExplorationSignal)},
  { 9, 16, sizeof(::llsf_msgs::ExplorationZone)},
  { 18, 25, sizeof(::llsf_msgs::ExplorationInfo)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::llsf_msgs::_ExplorationSignal_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::llsf_msgs::_ExplorationZone_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::llsf_msgs::_ExplorationInfo_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "ExplorationInfo.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025ExplorationInfo.proto\022\tllsf_msgs\032\021Mach"
      "ineInfo.proto\032\nTeam.proto\032\nZone.proto\"o\n"
      "\021ExplorationSignal\022\014\n\004type\030\001 \002(\t\022$\n\006ligh"
      "ts\030\002 \003(\0132\024.llsf_msgs.LightSpec\"&\n\010CompTy"
      "pe\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYPE\020F\"}\n\017Explor"
      "ationZone\022\035\n\004zone\030\002 \002(\0162\017.llsf_msgs.Zone"
      "\022#\n\nteam_color\030\003 \002(\0162\017.llsf_msgs.Team\"&\n"
      "\010CompType\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYPE\020G\"\223\001"
      "\n\017ExplorationInfo\022-\n\007signals\030\001 \003(\0132\034.lls"
      "f_msgs.ExplorationSignal\022)\n\005zones\030\002 \003(\0132"
      "\032.llsf_msgs.ExplorationZone\"&\n\010CompType\022"
      "\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYPE\020HB8\n\037org.roboc"
      "up_logistics.llsf_msgsB\025ExplorationInfoP"
      "rotos"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 525);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ExplorationInfo.proto", &protobuf_RegisterTypes);
  ::protobuf_MachineInfo_2eproto::AddDescriptors();
  ::protobuf_Team_2eproto::AddDescriptors();
  ::protobuf_Zone_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ExplorationInfo_2eproto
namespace llsf_msgs {
const ::google::protobuf::EnumDescriptor* ExplorationSignal_CompType_descriptor() {
  protobuf_ExplorationInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ExplorationInfo_2eproto::file_level_enum_descriptors[0];
}
bool ExplorationSignal_CompType_IsValid(int value) {
  switch (value) {
    case 70:
    case 2000:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const ExplorationSignal_CompType ExplorationSignal::COMP_ID;
const ExplorationSignal_CompType ExplorationSignal::MSG_TYPE;
const ExplorationSignal_CompType ExplorationSignal::CompType_MIN;
const ExplorationSignal_CompType ExplorationSignal::CompType_MAX;
const int ExplorationSignal::CompType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* ExplorationZone_CompType_descriptor() {
  protobuf_ExplorationInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ExplorationInfo_2eproto::file_level_enum_descriptors[1];
}
bool ExplorationZone_CompType_IsValid(int value) {
  switch (value) {
    case 71:
    case 2000:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const ExplorationZone_CompType ExplorationZone::COMP_ID;
const ExplorationZone_CompType ExplorationZone::MSG_TYPE;
const ExplorationZone_CompType ExplorationZone::CompType_MIN;
const ExplorationZone_CompType ExplorationZone::CompType_MAX;
const int ExplorationZone::CompType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* ExplorationInfo_CompType_descriptor() {
  protobuf_ExplorationInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_ExplorationInfo_2eproto::file_level_enum_descriptors[2];
}
bool ExplorationInfo_CompType_IsValid(int value) {
  switch (value) {
    case 72:
    case 2000:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const ExplorationInfo_CompType ExplorationInfo::COMP_ID;
const ExplorationInfo_CompType ExplorationInfo::MSG_TYPE;
const ExplorationInfo_CompType ExplorationInfo::CompType_MIN;
const ExplorationInfo_CompType ExplorationInfo::CompType_MAX;
const int ExplorationInfo::CompType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void ExplorationSignal::InitAsDefaultInstance() {
}
void ExplorationSignal::clear_lights() {
  lights_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ExplorationSignal::kTypeFieldNumber;
const int ExplorationSignal::kLightsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExplorationSignal::ExplorationSignal()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ExplorationInfo_2eproto::scc_info_ExplorationSignal.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:llsf_msgs.ExplorationSignal)
}
ExplorationSignal::ExplorationSignal(const ExplorationSignal& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      lights_(from.lights_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_type()) {
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  // @@protoc_insertion_point(copy_constructor:llsf_msgs.ExplorationSignal)
}

void ExplorationSignal::SharedCtor() {
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ExplorationSignal::~ExplorationSignal() {
  // @@protoc_insertion_point(destructor:llsf_msgs.ExplorationSignal)
  SharedDtor();
}

void ExplorationSignal::SharedDtor() {
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ExplorationSignal::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ExplorationSignal::descriptor() {
  ::protobuf_ExplorationInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ExplorationInfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ExplorationSignal& ExplorationSignal::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ExplorationInfo_2eproto::scc_info_ExplorationSignal.base);
  return *internal_default_instance();
}


void ExplorationSignal::Clear() {
// @@protoc_insertion_point(message_clear_start:llsf_msgs.ExplorationSignal)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  lights_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    type_.ClearNonDefaultToEmptyNoArena();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ExplorationSignal::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:llsf_msgs.ExplorationSignal)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->type().data(), static_cast<int>(this->type().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "llsf_msgs.ExplorationSignal.type");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .llsf_msgs.LightSpec lights = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_lights()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:llsf_msgs.ExplorationSignal)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:llsf_msgs.ExplorationSignal)
  return false;
#undef DO_
}

void ExplorationSignal::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:llsf_msgs.ExplorationSignal)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "llsf_msgs.ExplorationSignal.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->type(), output);
  }

  // repeated .llsf_msgs.LightSpec lights = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->lights_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->lights(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:llsf_msgs.ExplorationSignal)
}

::google::protobuf::uint8* ExplorationSignal::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:llsf_msgs.ExplorationSignal)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "llsf_msgs.ExplorationSignal.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->type(), target);
  }

  // repeated .llsf_msgs.LightSpec lights = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->lights_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->lights(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llsf_msgs.ExplorationSignal)
  return target;
}

size_t ExplorationSignal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llsf_msgs.ExplorationSignal)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required string type = 1;
  if (has_type()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }
  // repeated .llsf_msgs.LightSpec lights = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->lights_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->lights(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExplorationSignal::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:llsf_msgs.ExplorationSignal)
  GOOGLE_DCHECK_NE(&from, this);
  const ExplorationSignal* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ExplorationSignal>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:llsf_msgs.ExplorationSignal)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:llsf_msgs.ExplorationSignal)
    MergeFrom(*source);
  }
}

void ExplorationSignal::MergeFrom(const ExplorationSignal& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:llsf_msgs.ExplorationSignal)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  lights_.MergeFrom(from.lights_);
  if (from.has_type()) {
    set_has_type();
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
}

void ExplorationSignal::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:llsf_msgs.ExplorationSignal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExplorationSignal::CopyFrom(const ExplorationSignal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llsf_msgs.ExplorationSignal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExplorationSignal::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->lights())) return false;
  return true;
}

void ExplorationSignal::Swap(ExplorationSignal* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ExplorationSignal::InternalSwap(ExplorationSignal* other) {
  using std::swap;
  CastToBase(&lights_)->InternalSwap(CastToBase(&other->lights_));
  type_.Swap(&other->type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ExplorationSignal::GetMetadata() const {
  protobuf_ExplorationInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ExplorationInfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ExplorationZone::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ExplorationZone::kZoneFieldNumber;
const int ExplorationZone::kTeamColorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExplorationZone::ExplorationZone()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ExplorationInfo_2eproto::scc_info_ExplorationZone.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:llsf_msgs.ExplorationZone)
}
ExplorationZone::ExplorationZone(const ExplorationZone& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&team_color_, &from.team_color_,
    static_cast<size_t>(reinterpret_cast<char*>(&zone_) -
    reinterpret_cast<char*>(&team_color_)) + sizeof(zone_));
  // @@protoc_insertion_point(copy_constructor:llsf_msgs.ExplorationZone)
}

void ExplorationZone::SharedCtor() {
  team_color_ = 0;
  zone_ = 18;
}

ExplorationZone::~ExplorationZone() {
  // @@protoc_insertion_point(destructor:llsf_msgs.ExplorationZone)
  SharedDtor();
}

void ExplorationZone::SharedDtor() {
}

void ExplorationZone::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ExplorationZone::descriptor() {
  ::protobuf_ExplorationInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ExplorationInfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ExplorationZone& ExplorationZone::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ExplorationInfo_2eproto::scc_info_ExplorationZone.base);
  return *internal_default_instance();
}


void ExplorationZone::Clear() {
// @@protoc_insertion_point(message_clear_start:llsf_msgs.ExplorationZone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    team_color_ = 0;
    zone_ = 18;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ExplorationZone::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:llsf_msgs.ExplorationZone)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .llsf_msgs.Zone zone = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::llsf_msgs::Zone_IsValid(value)) {
            set_zone(static_cast< ::llsf_msgs::Zone >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                2, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .llsf_msgs.Team team_color = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::llsf_msgs::Team_IsValid(value)) {
            set_team_color(static_cast< ::llsf_msgs::Team >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                3, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:llsf_msgs.ExplorationZone)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:llsf_msgs.ExplorationZone)
  return false;
#undef DO_
}

void ExplorationZone::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:llsf_msgs.ExplorationZone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .llsf_msgs.Zone zone = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->zone(), output);
  }

  // required .llsf_msgs.Team team_color = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->team_color(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:llsf_msgs.ExplorationZone)
}

::google::protobuf::uint8* ExplorationZone::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:llsf_msgs.ExplorationZone)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .llsf_msgs.Zone zone = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->zone(), target);
  }

  // required .llsf_msgs.Team team_color = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->team_color(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llsf_msgs.ExplorationZone)
  return target;
}

size_t ExplorationZone::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:llsf_msgs.ExplorationZone)
  size_t total_size = 0;

  if (has_team_color()) {
    // required .llsf_msgs.Team team_color = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->team_color());
  }

  if (has_zone()) {
    // required .llsf_msgs.Zone zone = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->zone());
  }

  return total_size;
}
size_t ExplorationZone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llsf_msgs.ExplorationZone)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .llsf_msgs.Team team_color = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->team_color());

    // required .llsf_msgs.Zone zone = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->zone());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExplorationZone::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:llsf_msgs.ExplorationZone)
  GOOGLE_DCHECK_NE(&from, this);
  const ExplorationZone* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ExplorationZone>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:llsf_msgs.ExplorationZone)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:llsf_msgs.ExplorationZone)
    MergeFrom(*source);
  }
}

void ExplorationZone::MergeFrom(const ExplorationZone& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:llsf_msgs.ExplorationZone)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      team_color_ = from.team_color_;
    }
    if (cached_has_bits & 0x00000002u) {
      zone_ = from.zone_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ExplorationZone::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:llsf_msgs.ExplorationZone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExplorationZone::CopyFrom(const ExplorationZone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llsf_msgs.ExplorationZone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExplorationZone::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void ExplorationZone::Swap(ExplorationZone* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ExplorationZone::InternalSwap(ExplorationZone* other) {
  using std::swap;
  swap(team_color_, other->team_color_);
  swap(zone_, other->zone_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ExplorationZone::GetMetadata() const {
  protobuf_ExplorationInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ExplorationInfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ExplorationInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ExplorationInfo::kSignalsFieldNumber;
const int ExplorationInfo::kZonesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExplorationInfo::ExplorationInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ExplorationInfo_2eproto::scc_info_ExplorationInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:llsf_msgs.ExplorationInfo)
}
ExplorationInfo::ExplorationInfo(const ExplorationInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      signals_(from.signals_),
      zones_(from.zones_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:llsf_msgs.ExplorationInfo)
}

void ExplorationInfo::SharedCtor() {
}

ExplorationInfo::~ExplorationInfo() {
  // @@protoc_insertion_point(destructor:llsf_msgs.ExplorationInfo)
  SharedDtor();
}

void ExplorationInfo::SharedDtor() {
}

void ExplorationInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ExplorationInfo::descriptor() {
  ::protobuf_ExplorationInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ExplorationInfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ExplorationInfo& ExplorationInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ExplorationInfo_2eproto::scc_info_ExplorationInfo.base);
  return *internal_default_instance();
}


void ExplorationInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:llsf_msgs.ExplorationInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  signals_.Clear();
  zones_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ExplorationInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:llsf_msgs.ExplorationInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .llsf_msgs.ExplorationSignal signals = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_signals()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .llsf_msgs.ExplorationZone zones = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_zones()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:llsf_msgs.ExplorationInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:llsf_msgs.ExplorationInfo)
  return false;
#undef DO_
}

void ExplorationInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:llsf_msgs.ExplorationInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .llsf_msgs.ExplorationSignal signals = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->signals_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->signals(static_cast<int>(i)),
      output);
  }

  // repeated .llsf_msgs.ExplorationZone zones = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->zones_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->zones(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:llsf_msgs.ExplorationInfo)
}

::google::protobuf::uint8* ExplorationInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:llsf_msgs.ExplorationInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .llsf_msgs.ExplorationSignal signals = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->signals_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->signals(static_cast<int>(i)), deterministic, target);
  }

  // repeated .llsf_msgs.ExplorationZone zones = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->zones_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->zones(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llsf_msgs.ExplorationInfo)
  return target;
}

size_t ExplorationInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llsf_msgs.ExplorationInfo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .llsf_msgs.ExplorationSignal signals = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->signals_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->signals(static_cast<int>(i)));
    }
  }

  // repeated .llsf_msgs.ExplorationZone zones = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->zones_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->zones(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ExplorationInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:llsf_msgs.ExplorationInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ExplorationInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ExplorationInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:llsf_msgs.ExplorationInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:llsf_msgs.ExplorationInfo)
    MergeFrom(*source);
  }
}

void ExplorationInfo::MergeFrom(const ExplorationInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:llsf_msgs.ExplorationInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  signals_.MergeFrom(from.signals_);
  zones_.MergeFrom(from.zones_);
}

void ExplorationInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:llsf_msgs.ExplorationInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExplorationInfo::CopyFrom(const ExplorationInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llsf_msgs.ExplorationInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExplorationInfo::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->signals())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->zones())) return false;
  return true;
}

void ExplorationInfo::Swap(ExplorationInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ExplorationInfo::InternalSwap(ExplorationInfo* other) {
  using std::swap;
  CastToBase(&signals_)->InternalSwap(CastToBase(&other->signals_));
  CastToBase(&zones_)->InternalSwap(CastToBase(&other->zones_));
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ExplorationInfo::GetMetadata() const {
  protobuf_ExplorationInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ExplorationInfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace llsf_msgs
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::llsf_msgs::ExplorationSignal* Arena::CreateMaybeMessage< ::llsf_msgs::ExplorationSignal >(Arena* arena) {
  return Arena::CreateInternal< ::llsf_msgs::ExplorationSignal >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::llsf_msgs::ExplorationZone* Arena::CreateMaybeMessage< ::llsf_msgs::ExplorationZone >(Arena* arena) {
  return Arena::CreateInternal< ::llsf_msgs::ExplorationZone >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::llsf_msgs::ExplorationInfo* Arena::CreateMaybeMessage< ::llsf_msgs::ExplorationInfo >(Arena* arena) {
  return Arena::CreateInternal< ::llsf_msgs::ExplorationInfo >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
