// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MachineCommands.proto

#include "MachineCommands.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_MachineInfo_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_MachineInfo_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_LightSpec;
}  // namespace protobuf_MachineInfo_2eproto
namespace llsf_msgs {
class SetMachineStateDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SetMachineState>
      _instance;
} _SetMachineState_default_instance_;
class MachineAddBaseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MachineAddBase>
      _instance;
} _MachineAddBase_default_instance_;
class SetMachineLightsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SetMachineLights>
      _instance;
} _SetMachineLights_default_instance_;
}  // namespace llsf_msgs
namespace protobuf_MachineCommands_2eproto {
static void InitDefaultsSetMachineState() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::llsf_msgs::_SetMachineState_default_instance_;
    new (ptr) ::llsf_msgs::SetMachineState();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::llsf_msgs::SetMachineState::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SetMachineState =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSetMachineState}, {}};

static void InitDefaultsMachineAddBase() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::llsf_msgs::_MachineAddBase_default_instance_;
    new (ptr) ::llsf_msgs::MachineAddBase();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::llsf_msgs::MachineAddBase::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MachineAddBase =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMachineAddBase}, {}};

static void InitDefaultsSetMachineLights() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::llsf_msgs::_SetMachineLights_default_instance_;
    new (ptr) ::llsf_msgs::SetMachineLights();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::llsf_msgs::SetMachineLights::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_SetMachineLights =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsSetMachineLights}, {
      &protobuf_MachineInfo_2eproto::scc_info_LightSpec.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SetMachineState.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MachineAddBase.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SetMachineLights.base);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetMachineState, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetMachineState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetMachineState, machine_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetMachineState, state_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::MachineAddBase, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::MachineAddBase, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::MachineAddBase, machine_name_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetMachineLights, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetMachineLights, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetMachineLights, machine_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetMachineLights, lights_),
  0,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::llsf_msgs::SetMachineState)},
  { 9, 15, sizeof(::llsf_msgs::MachineAddBase)},
  { 16, 23, sizeof(::llsf_msgs::SetMachineLights)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::llsf_msgs::_SetMachineState_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::llsf_msgs::_MachineAddBase_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::llsf_msgs::_SetMachineLights_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "MachineCommands.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025MachineCommands.proto\022\tllsf_msgs\032\021Mach"
      "ineInfo.proto\"w\n\017SetMachineState\022\024\n\014mach"
      "ine_name\030\001 \002(\t\022&\n\005state\030\002 \002(\0162\027.llsf_msg"
      "s.MachineState\"&\n\010CompType\022\014\n\007COMP_ID\020\320\017"
      "\022\014\n\010MSG_TYPE\020\021\"N\n\016MachineAddBase\022\024\n\014mach"
      "ine_name\030\001 \002(\t\"&\n\010CompType\022\014\n\007COMP_ID\020\320\017"
      "\022\014\n\010MSG_TYPE\020\022\"v\n\020SetMachineLights\022\024\n\014ma"
      "chine_name\030\001 \002(\t\022$\n\006lights\030\002 \003(\0132\024.llsf_"
      "msgs.LightSpec\"&\n\010CompType\022\014\n\007COMP_ID\020\320\017"
      "\022\014\n\010MSG_TYPE\020\023*_\n\014MachineState\022\010\n\004IDLE\020\001"
      "\022\r\n\tAVAILABLE\020\002\022\r\n\tPROCESSED\020\003\022\r\n\tDELIVE"
      "RED\020\004\022\r\n\tRETRIEVED\020\005\022\t\n\005RESET\020\017B8\n\037org.r"
      "obocup_logistics.llsf_msgsB\025MachineComma"
      "ndsProtos"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 529);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MachineCommands.proto", &protobuf_RegisterTypes);
  ::protobuf_MachineInfo_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_MachineCommands_2eproto
namespace llsf_msgs {
const ::google::protobuf::EnumDescriptor* SetMachineState_CompType_descriptor() {
  protobuf_MachineCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MachineCommands_2eproto::file_level_enum_descriptors[0];
}
bool SetMachineState_CompType_IsValid(int value) {
  switch (value) {
    case 17:
    case 2000:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const SetMachineState_CompType SetMachineState::COMP_ID;
const SetMachineState_CompType SetMachineState::MSG_TYPE;
const SetMachineState_CompType SetMachineState::CompType_MIN;
const SetMachineState_CompType SetMachineState::CompType_MAX;
const int SetMachineState::CompType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* MachineAddBase_CompType_descriptor() {
  protobuf_MachineCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MachineCommands_2eproto::file_level_enum_descriptors[1];
}
bool MachineAddBase_CompType_IsValid(int value) {
  switch (value) {
    case 18:
    case 2000:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const MachineAddBase_CompType MachineAddBase::COMP_ID;
const MachineAddBase_CompType MachineAddBase::MSG_TYPE;
const MachineAddBase_CompType MachineAddBase::CompType_MIN;
const MachineAddBase_CompType MachineAddBase::CompType_MAX;
const int MachineAddBase::CompType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* SetMachineLights_CompType_descriptor() {
  protobuf_MachineCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MachineCommands_2eproto::file_level_enum_descriptors[2];
}
bool SetMachineLights_CompType_IsValid(int value) {
  switch (value) {
    case 19:
    case 2000:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const SetMachineLights_CompType SetMachineLights::COMP_ID;
const SetMachineLights_CompType SetMachineLights::MSG_TYPE;
const SetMachineLights_CompType SetMachineLights::CompType_MIN;
const SetMachineLights_CompType SetMachineLights::CompType_MAX;
const int SetMachineLights::CompType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* MachineState_descriptor() {
  protobuf_MachineCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MachineCommands_2eproto::file_level_enum_descriptors[3];
}
bool MachineState_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 15:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void SetMachineState::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SetMachineState::kMachineNameFieldNumber;
const int SetMachineState::kStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SetMachineState::SetMachineState()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MachineCommands_2eproto::scc_info_SetMachineState.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:llsf_msgs.SetMachineState)
}
SetMachineState::SetMachineState(const SetMachineState& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  machine_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_machine_name()) {
    machine_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.machine_name_);
  }
  state_ = from.state_;
  // @@protoc_insertion_point(copy_constructor:llsf_msgs.SetMachineState)
}

void SetMachineState::SharedCtor() {
  machine_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  state_ = 1;
}

SetMachineState::~SetMachineState() {
  // @@protoc_insertion_point(destructor:llsf_msgs.SetMachineState)
  SharedDtor();
}

void SetMachineState::SharedDtor() {
  machine_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SetMachineState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SetMachineState::descriptor() {
  ::protobuf_MachineCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MachineCommands_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SetMachineState& SetMachineState::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MachineCommands_2eproto::scc_info_SetMachineState.base);
  return *internal_default_instance();
}


void SetMachineState::Clear() {
// @@protoc_insertion_point(message_clear_start:llsf_msgs.SetMachineState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      machine_name_.ClearNonDefaultToEmptyNoArena();
    }
    state_ = 1;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SetMachineState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:llsf_msgs.SetMachineState)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string machine_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_machine_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->machine_name().data(), static_cast<int>(this->machine_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "llsf_msgs.SetMachineState.machine_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .llsf_msgs.MachineState state = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::llsf_msgs::MachineState_IsValid(value)) {
            set_state(static_cast< ::llsf_msgs::MachineState >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                2, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:llsf_msgs.SetMachineState)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:llsf_msgs.SetMachineState)
  return false;
#undef DO_
}

void SetMachineState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:llsf_msgs.SetMachineState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string machine_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machine_name().data(), static_cast<int>(this->machine_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "llsf_msgs.SetMachineState.machine_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->machine_name(), output);
  }

  // required .llsf_msgs.MachineState state = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->state(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:llsf_msgs.SetMachineState)
}

::google::protobuf::uint8* SetMachineState::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:llsf_msgs.SetMachineState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string machine_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machine_name().data(), static_cast<int>(this->machine_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "llsf_msgs.SetMachineState.machine_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->machine_name(), target);
  }

  // required .llsf_msgs.MachineState state = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->state(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llsf_msgs.SetMachineState)
  return target;
}

size_t SetMachineState::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:llsf_msgs.SetMachineState)
  size_t total_size = 0;

  if (has_machine_name()) {
    // required string machine_name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->machine_name());
  }

  if (has_state()) {
    // required .llsf_msgs.MachineState state = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->state());
  }

  return total_size;
}
size_t SetMachineState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llsf_msgs.SetMachineState)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string machine_name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->machine_name());

    // required .llsf_msgs.MachineState state = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->state());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SetMachineState::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:llsf_msgs.SetMachineState)
  GOOGLE_DCHECK_NE(&from, this);
  const SetMachineState* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SetMachineState>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:llsf_msgs.SetMachineState)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:llsf_msgs.SetMachineState)
    MergeFrom(*source);
  }
}

void SetMachineState::MergeFrom(const SetMachineState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:llsf_msgs.SetMachineState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_machine_name();
      machine_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.machine_name_);
    }
    if (cached_has_bits & 0x00000002u) {
      state_ = from.state_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SetMachineState::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:llsf_msgs.SetMachineState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SetMachineState::CopyFrom(const SetMachineState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llsf_msgs.SetMachineState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetMachineState::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void SetMachineState::Swap(SetMachineState* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SetMachineState::InternalSwap(SetMachineState* other) {
  using std::swap;
  machine_name_.Swap(&other->machine_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(state_, other->state_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SetMachineState::GetMetadata() const {
  protobuf_MachineCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MachineCommands_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MachineAddBase::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MachineAddBase::kMachineNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MachineAddBase::MachineAddBase()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MachineCommands_2eproto::scc_info_MachineAddBase.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:llsf_msgs.MachineAddBase)
}
MachineAddBase::MachineAddBase(const MachineAddBase& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  machine_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_machine_name()) {
    machine_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.machine_name_);
  }
  // @@protoc_insertion_point(copy_constructor:llsf_msgs.MachineAddBase)
}

void MachineAddBase::SharedCtor() {
  machine_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MachineAddBase::~MachineAddBase() {
  // @@protoc_insertion_point(destructor:llsf_msgs.MachineAddBase)
  SharedDtor();
}

void MachineAddBase::SharedDtor() {
  machine_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MachineAddBase::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MachineAddBase::descriptor() {
  ::protobuf_MachineCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MachineCommands_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MachineAddBase& MachineAddBase::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MachineCommands_2eproto::scc_info_MachineAddBase.base);
  return *internal_default_instance();
}


void MachineAddBase::Clear() {
// @@protoc_insertion_point(message_clear_start:llsf_msgs.MachineAddBase)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    machine_name_.ClearNonDefaultToEmptyNoArena();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool MachineAddBase::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:llsf_msgs.MachineAddBase)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string machine_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_machine_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->machine_name().data(), static_cast<int>(this->machine_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "llsf_msgs.MachineAddBase.machine_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:llsf_msgs.MachineAddBase)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:llsf_msgs.MachineAddBase)
  return false;
#undef DO_
}

void MachineAddBase::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:llsf_msgs.MachineAddBase)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string machine_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machine_name().data(), static_cast<int>(this->machine_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "llsf_msgs.MachineAddBase.machine_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->machine_name(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:llsf_msgs.MachineAddBase)
}

::google::protobuf::uint8* MachineAddBase::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:llsf_msgs.MachineAddBase)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string machine_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machine_name().data(), static_cast<int>(this->machine_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "llsf_msgs.MachineAddBase.machine_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->machine_name(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llsf_msgs.MachineAddBase)
  return target;
}

size_t MachineAddBase::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llsf_msgs.MachineAddBase)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required string machine_name = 1;
  if (has_machine_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->machine_name());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MachineAddBase::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:llsf_msgs.MachineAddBase)
  GOOGLE_DCHECK_NE(&from, this);
  const MachineAddBase* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MachineAddBase>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:llsf_msgs.MachineAddBase)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:llsf_msgs.MachineAddBase)
    MergeFrom(*source);
  }
}

void MachineAddBase::MergeFrom(const MachineAddBase& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:llsf_msgs.MachineAddBase)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_machine_name()) {
    set_has_machine_name();
    machine_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.machine_name_);
  }
}

void MachineAddBase::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:llsf_msgs.MachineAddBase)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MachineAddBase::CopyFrom(const MachineAddBase& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llsf_msgs.MachineAddBase)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MachineAddBase::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void MachineAddBase::Swap(MachineAddBase* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MachineAddBase::InternalSwap(MachineAddBase* other) {
  using std::swap;
  machine_name_.Swap(&other->machine_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MachineAddBase::GetMetadata() const {
  protobuf_MachineCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MachineCommands_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SetMachineLights::InitAsDefaultInstance() {
}
void SetMachineLights::clear_lights() {
  lights_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SetMachineLights::kMachineNameFieldNumber;
const int SetMachineLights::kLightsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SetMachineLights::SetMachineLights()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MachineCommands_2eproto::scc_info_SetMachineLights.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:llsf_msgs.SetMachineLights)
}
SetMachineLights::SetMachineLights(const SetMachineLights& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      lights_(from.lights_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  machine_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_machine_name()) {
    machine_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.machine_name_);
  }
  // @@protoc_insertion_point(copy_constructor:llsf_msgs.SetMachineLights)
}

void SetMachineLights::SharedCtor() {
  machine_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

SetMachineLights::~SetMachineLights() {
  // @@protoc_insertion_point(destructor:llsf_msgs.SetMachineLights)
  SharedDtor();
}

void SetMachineLights::SharedDtor() {
  machine_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SetMachineLights::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SetMachineLights::descriptor() {
  ::protobuf_MachineCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MachineCommands_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SetMachineLights& SetMachineLights::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MachineCommands_2eproto::scc_info_SetMachineLights.base);
  return *internal_default_instance();
}


void SetMachineLights::Clear() {
// @@protoc_insertion_point(message_clear_start:llsf_msgs.SetMachineLights)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  lights_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    machine_name_.ClearNonDefaultToEmptyNoArena();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SetMachineLights::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:llsf_msgs.SetMachineLights)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string machine_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_machine_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->machine_name().data(), static_cast<int>(this->machine_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "llsf_msgs.SetMachineLights.machine_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .llsf_msgs.LightSpec lights = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_lights()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:llsf_msgs.SetMachineLights)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:llsf_msgs.SetMachineLights)
  return false;
#undef DO_
}

void SetMachineLights::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:llsf_msgs.SetMachineLights)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string machine_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machine_name().data(), static_cast<int>(this->machine_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "llsf_msgs.SetMachineLights.machine_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->machine_name(), output);
  }

  // repeated .llsf_msgs.LightSpec lights = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->lights_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->lights(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:llsf_msgs.SetMachineLights)
}

::google::protobuf::uint8* SetMachineLights::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:llsf_msgs.SetMachineLights)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string machine_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machine_name().data(), static_cast<int>(this->machine_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "llsf_msgs.SetMachineLights.machine_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->machine_name(), target);
  }

  // repeated .llsf_msgs.LightSpec lights = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->lights_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->lights(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llsf_msgs.SetMachineLights)
  return target;
}

size_t SetMachineLights::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llsf_msgs.SetMachineLights)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required string machine_name = 1;
  if (has_machine_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->machine_name());
  }
  // repeated .llsf_msgs.LightSpec lights = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->lights_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->lights(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SetMachineLights::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:llsf_msgs.SetMachineLights)
  GOOGLE_DCHECK_NE(&from, this);
  const SetMachineLights* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SetMachineLights>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:llsf_msgs.SetMachineLights)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:llsf_msgs.SetMachineLights)
    MergeFrom(*source);
  }
}

void SetMachineLights::MergeFrom(const SetMachineLights& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:llsf_msgs.SetMachineLights)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  lights_.MergeFrom(from.lights_);
  if (from.has_machine_name()) {
    set_has_machine_name();
    machine_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.machine_name_);
  }
}

void SetMachineLights::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:llsf_msgs.SetMachineLights)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SetMachineLights::CopyFrom(const SetMachineLights& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llsf_msgs.SetMachineLights)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetMachineLights::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->lights())) return false;
  return true;
}

void SetMachineLights::Swap(SetMachineLights* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SetMachineLights::InternalSwap(SetMachineLights* other) {
  using std::swap;
  CastToBase(&lights_)->InternalSwap(CastToBase(&other->lights_));
  machine_name_.Swap(&other->machine_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SetMachineLights::GetMetadata() const {
  protobuf_MachineCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MachineCommands_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace llsf_msgs
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::llsf_msgs::SetMachineState* Arena::CreateMaybeMessage< ::llsf_msgs::SetMachineState >(Arena* arena) {
  return Arena::CreateInternal< ::llsf_msgs::SetMachineState >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::llsf_msgs::MachineAddBase* Arena::CreateMaybeMessage< ::llsf_msgs::MachineAddBase >(Arena* arena) {
  return Arena::CreateInternal< ::llsf_msgs::MachineAddBase >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::llsf_msgs::SetMachineLights* Arena::CreateMaybeMessage< ::llsf_msgs::SetMachineLights >(Arena* arena) {
  return Arena::CreateInternal< ::llsf_msgs::SetMachineLights >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
