// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RobotCommands.proto

#include "RobotCommands.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace llsf_msgs {
class SetRobotMaintenanceDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SetRobotMaintenance>
      _instance;
} _SetRobotMaintenance_default_instance_;
}  // namespace llsf_msgs
namespace protobuf_RobotCommands_2eproto {
static void InitDefaultsSetRobotMaintenance() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::llsf_msgs::_SetRobotMaintenance_default_instance_;
    new (ptr) ::llsf_msgs::SetRobotMaintenance();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::llsf_msgs::SetRobotMaintenance::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SetRobotMaintenance =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSetRobotMaintenance}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SetRobotMaintenance.base);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetRobotMaintenance, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetRobotMaintenance, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetRobotMaintenance, robot_number_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetRobotMaintenance, maintenance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::llsf_msgs::SetRobotMaintenance, team_color_),
  0,
  1,
  2,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::llsf_msgs::SetRobotMaintenance)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::llsf_msgs::_SetRobotMaintenance_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "RobotCommands.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023RobotCommands.proto\022\tllsf_msgs\032\nTeam.p"
      "roto\"\215\001\n\023SetRobotMaintenance\022\024\n\014robot_nu"
      "mber\030\001 \002(\r\022\023\n\013maintenance\030\003 \002(\010\022#\n\nteam_"
      "color\030\004 \002(\0162\017.llsf_msgs.Team\"&\n\010CompType"
      "\022\014\n\007COMP_ID\020\320\017\022\014\n\010MSG_TYPE\020[B6\n\037org.robo"
      "cup_logistics.llsf_msgsB\023RobotCommandsPr"
      "otos"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 244);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RobotCommands.proto", &protobuf_RegisterTypes);
  ::protobuf_Team_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_RobotCommands_2eproto
namespace llsf_msgs {
const ::google::protobuf::EnumDescriptor* SetRobotMaintenance_CompType_descriptor() {
  protobuf_RobotCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RobotCommands_2eproto::file_level_enum_descriptors[0];
}
bool SetRobotMaintenance_CompType_IsValid(int value) {
  switch (value) {
    case 91:
    case 2000:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const SetRobotMaintenance_CompType SetRobotMaintenance::COMP_ID;
const SetRobotMaintenance_CompType SetRobotMaintenance::MSG_TYPE;
const SetRobotMaintenance_CompType SetRobotMaintenance::CompType_MIN;
const SetRobotMaintenance_CompType SetRobotMaintenance::CompType_MAX;
const int SetRobotMaintenance::CompType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void SetRobotMaintenance::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SetRobotMaintenance::kRobotNumberFieldNumber;
const int SetRobotMaintenance::kMaintenanceFieldNumber;
const int SetRobotMaintenance::kTeamColorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SetRobotMaintenance::SetRobotMaintenance()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_RobotCommands_2eproto::scc_info_SetRobotMaintenance.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:llsf_msgs.SetRobotMaintenance)
}
SetRobotMaintenance::SetRobotMaintenance(const SetRobotMaintenance& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&robot_number_, &from.robot_number_,
    static_cast<size_t>(reinterpret_cast<char*>(&team_color_) -
    reinterpret_cast<char*>(&robot_number_)) + sizeof(team_color_));
  // @@protoc_insertion_point(copy_constructor:llsf_msgs.SetRobotMaintenance)
}

void SetRobotMaintenance::SharedCtor() {
  ::memset(&robot_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&team_color_) -
      reinterpret_cast<char*>(&robot_number_)) + sizeof(team_color_));
}

SetRobotMaintenance::~SetRobotMaintenance() {
  // @@protoc_insertion_point(destructor:llsf_msgs.SetRobotMaintenance)
  SharedDtor();
}

void SetRobotMaintenance::SharedDtor() {
}

void SetRobotMaintenance::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SetRobotMaintenance::descriptor() {
  ::protobuf_RobotCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RobotCommands_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SetRobotMaintenance& SetRobotMaintenance::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_RobotCommands_2eproto::scc_info_SetRobotMaintenance.base);
  return *internal_default_instance();
}


void SetRobotMaintenance::Clear() {
// @@protoc_insertion_point(message_clear_start:llsf_msgs.SetRobotMaintenance)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    ::memset(&robot_number_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&team_color_) -
        reinterpret_cast<char*>(&robot_number_)) + sizeof(team_color_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SetRobotMaintenance::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:llsf_msgs.SetRobotMaintenance)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 robot_number = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_robot_number();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &robot_number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bool maintenance = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          set_has_maintenance();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &maintenance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .llsf_msgs.Team team_color = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::llsf_msgs::Team_IsValid(value)) {
            set_team_color(static_cast< ::llsf_msgs::Team >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                4, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:llsf_msgs.SetRobotMaintenance)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:llsf_msgs.SetRobotMaintenance)
  return false;
#undef DO_
}

void SetRobotMaintenance::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:llsf_msgs.SetRobotMaintenance)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 robot_number = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->robot_number(), output);
  }

  // required bool maintenance = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->maintenance(), output);
  }

  // required .llsf_msgs.Team team_color = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->team_color(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:llsf_msgs.SetRobotMaintenance)
}

::google::protobuf::uint8* SetRobotMaintenance::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:llsf_msgs.SetRobotMaintenance)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 robot_number = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->robot_number(), target);
  }

  // required bool maintenance = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->maintenance(), target);
  }

  // required .llsf_msgs.Team team_color = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->team_color(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:llsf_msgs.SetRobotMaintenance)
  return target;
}

size_t SetRobotMaintenance::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:llsf_msgs.SetRobotMaintenance)
  size_t total_size = 0;

  if (has_robot_number()) {
    // required uint32 robot_number = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->robot_number());
  }

  if (has_maintenance()) {
    // required bool maintenance = 3;
    total_size += 1 + 1;
  }

  if (has_team_color()) {
    // required .llsf_msgs.Team team_color = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->team_color());
  }

  return total_size;
}
size_t SetRobotMaintenance::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:llsf_msgs.SetRobotMaintenance)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required uint32 robot_number = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->robot_number());

    // required bool maintenance = 3;
    total_size += 1 + 1;

    // required .llsf_msgs.Team team_color = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->team_color());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SetRobotMaintenance::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:llsf_msgs.SetRobotMaintenance)
  GOOGLE_DCHECK_NE(&from, this);
  const SetRobotMaintenance* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SetRobotMaintenance>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:llsf_msgs.SetRobotMaintenance)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:llsf_msgs.SetRobotMaintenance)
    MergeFrom(*source);
  }
}

void SetRobotMaintenance::MergeFrom(const SetRobotMaintenance& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:llsf_msgs.SetRobotMaintenance)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      robot_number_ = from.robot_number_;
    }
    if (cached_has_bits & 0x00000002u) {
      maintenance_ = from.maintenance_;
    }
    if (cached_has_bits & 0x00000004u) {
      team_color_ = from.team_color_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SetRobotMaintenance::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:llsf_msgs.SetRobotMaintenance)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SetRobotMaintenance::CopyFrom(const SetRobotMaintenance& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:llsf_msgs.SetRobotMaintenance)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetRobotMaintenance::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void SetRobotMaintenance::Swap(SetRobotMaintenance* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SetRobotMaintenance::InternalSwap(SetRobotMaintenance* other) {
  using std::swap;
  swap(robot_number_, other->robot_number_);
  swap(maintenance_, other->maintenance_);
  swap(team_color_, other->team_color_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SetRobotMaintenance::GetMetadata() const {
  protobuf_RobotCommands_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RobotCommands_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace llsf_msgs
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::llsf_msgs::SetRobotMaintenance* Arena::CreateMaybeMessage< ::llsf_msgs::SetRobotMaintenance >(Arena* arena) {
  return Arena::CreateInternal< ::llsf_msgs::SetRobotMaintenance >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
