# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgentTask.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Team_pb2 as Team__pb2
import ProductColor_pb2 as ProductColor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgentTask.proto',
  package='llsf_msgs',
  syntax='proto2',
  serialized_options=_b('\n\037org.robocup_logistics.llsf_msgsB\020AgentTasksProtos'),
  serialized_pb=_b('\n\x0f\x41gentTask.proto\x12\tllsf_msgs\x1a\nTeam.proto\x1a\x12ProductColor.proto\"\xfb\x03\n\tAgentTask\x12#\n\nteam_color\x18\x01 \x02(\x0e\x32\x0f.llsf_msgs.Team\x12\x0f\n\x07task_id\x18\x02 \x02(\r\x12\x10\n\x08robot_id\x18\x03 \x02(\r\x12\x1d\n\x04move\x18\x04 \x01(\x0b\x32\x0f.llsf_msgs.Move\x12%\n\x08retrieve\x18\x05 \x01(\x0b\x32\x13.llsf_msgs.Retrieve\x12#\n\x07\x64\x65liver\x18\x06 \x01(\x0b\x32\x12.llsf_msgs.Deliver\x12(\n\x06\x62uffer\x18\x07 \x01(\x0b\x32\x18.llsf_msgs.BufferStation\x12\x33\n\x0f\x65xplore_machine\x18\x08 \x01(\x0b\x32\x1a.llsf_msgs.ExploreWaypoint\x12>\n\x15workpiece_description\x18\t \x01(\x0b\x32\x1f.llsf_msgs.WorkpieceDescription\x12\x10\n\x08order_id\x18\n \x01(\r\x12\x13\n\x0b\x63\x61ncel_task\x18\x0b \x01(\x08\x12\x12\n\npause_task\x18\x0c \x01(\x08\x12\x12\n\nsuccessful\x18\r \x01(\x08\x12\x10\n\x08\x63\x61nceled\x18\x0e \x01(\x08\x12\x12\n\nerror_code\x18\x0f \x01(\r\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xc0>\x12\r\n\x08MSG_TYPE\x10\xf6\x03\"/\n\x04Move\x12\x10\n\x08waypoint\x18\x01 \x02(\t\x12\x15\n\rmachine_point\x18\x02 \x01(\t\"5\n\x08Retrieve\x12\x12\n\nmachine_id\x18\x01 \x02(\t\x12\x15\n\rmachine_point\x18\x02 \x02(\t\"4\n\x07\x44\x65liver\x12\x12\n\nmachine_id\x18\x01 \x02(\t\x12\x15\n\rmachine_point\x18\x02 \x02(\t\"9\n\rBufferStation\x12\x12\n\nmachine_id\x18\x01 \x02(\t\x12\x14\n\x0cshelf_number\x18\x02 \x02(\r\"N\n\x0f\x45xploreWaypoint\x12\x12\n\nmachine_id\x18\x01 \x02(\t\x12\x15\n\rmachine_point\x18\x02 \x02(\t\x12\x10\n\x08waypoint\x18\x03 \x02(\t\"\xbc\x01\n\x14WorkpieceDescription\x12(\n\nbase_color\x18\x03 \x02(\x0e\x32\x14.llsf_msgs.BaseColor\x12)\n\x0bring_colors\x18\x04 \x03(\x0e\x32\x14.llsf_msgs.RingColor\x12&\n\tcap_color\x18\x05 \x01(\x0e\x32\x13.llsf_msgs.CapColor\"\'\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xc0>\x12\r\n\x08MSG_TYPE\x10\xfe\x03\x42\x33\n\x1forg.robocup_logistics.llsf_msgsB\x10\x41gentTasksProtos')
  ,
  dependencies=[Team__pb2.DESCRIPTOR,ProductColor__pb2.DESCRIPTOR,])



_AGENTTASK_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='llsf_msgs.AgentTask.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=8000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=502,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=531,
  serialized_end=570,
)
_sym_db.RegisterEnumDescriptor(_AGENTTASK_COMPTYPE)

_WORKPIECEDESCRIPTION_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='llsf_msgs.WorkpieceDescription.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=8000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=510,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1019,
  serialized_end=1058,
)
_sym_db.RegisterEnumDescriptor(_WORKPIECEDESCRIPTION_COMPTYPE)


_AGENTTASK = _descriptor.Descriptor(
  name='AgentTask',
  full_name='llsf_msgs.AgentTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_color', full_name='llsf_msgs.AgentTask.team_color', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_id', full_name='llsf_msgs.AgentTask.task_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='llsf_msgs.AgentTask.robot_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move', full_name='llsf_msgs.AgentTask.move', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='retrieve', full_name='llsf_msgs.AgentTask.retrieve', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deliver', full_name='llsf_msgs.AgentTask.deliver', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buffer', full_name='llsf_msgs.AgentTask.buffer', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='explore_machine', full_name='llsf_msgs.AgentTask.explore_machine', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workpiece_description', full_name='llsf_msgs.AgentTask.workpiece_description', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_id', full_name='llsf_msgs.AgentTask.order_id', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cancel_task', full_name='llsf_msgs.AgentTask.cancel_task', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pause_task', full_name='llsf_msgs.AgentTask.pause_task', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='successful', full_name='llsf_msgs.AgentTask.successful', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='canceled', full_name='llsf_msgs.AgentTask.canceled', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='llsf_msgs.AgentTask.error_code', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AGENTTASK_COMPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=570,
)


_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='llsf_msgs.Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='waypoint', full_name='llsf_msgs.Move.waypoint', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_point', full_name='llsf_msgs.Move.machine_point', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=572,
  serialized_end=619,
)


_RETRIEVE = _descriptor.Descriptor(
  name='Retrieve',
  full_name='llsf_msgs.Retrieve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine_id', full_name='llsf_msgs.Retrieve.machine_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_point', full_name='llsf_msgs.Retrieve.machine_point', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=621,
  serialized_end=674,
)


_DELIVER = _descriptor.Descriptor(
  name='Deliver',
  full_name='llsf_msgs.Deliver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine_id', full_name='llsf_msgs.Deliver.machine_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_point', full_name='llsf_msgs.Deliver.machine_point', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=676,
  serialized_end=728,
)


_BUFFERSTATION = _descriptor.Descriptor(
  name='BufferStation',
  full_name='llsf_msgs.BufferStation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine_id', full_name='llsf_msgs.BufferStation.machine_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shelf_number', full_name='llsf_msgs.BufferStation.shelf_number', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=730,
  serialized_end=787,
)


_EXPLOREWAYPOINT = _descriptor.Descriptor(
  name='ExploreWaypoint',
  full_name='llsf_msgs.ExploreWaypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine_id', full_name='llsf_msgs.ExploreWaypoint.machine_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_point', full_name='llsf_msgs.ExploreWaypoint.machine_point', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='waypoint', full_name='llsf_msgs.ExploreWaypoint.waypoint', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=789,
  serialized_end=867,
)


_WORKPIECEDESCRIPTION = _descriptor.Descriptor(
  name='WorkpieceDescription',
  full_name='llsf_msgs.WorkpieceDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_color', full_name='llsf_msgs.WorkpieceDescription.base_color', index=0,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ring_colors', full_name='llsf_msgs.WorkpieceDescription.ring_colors', index=1,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cap_color', full_name='llsf_msgs.WorkpieceDescription.cap_color', index=2,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WORKPIECEDESCRIPTION_COMPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=870,
  serialized_end=1058,
)

_AGENTTASK.fields_by_name['team_color'].enum_type = Team__pb2._TEAM
_AGENTTASK.fields_by_name['move'].message_type = _MOVE
_AGENTTASK.fields_by_name['retrieve'].message_type = _RETRIEVE
_AGENTTASK.fields_by_name['deliver'].message_type = _DELIVER
_AGENTTASK.fields_by_name['buffer'].message_type = _BUFFERSTATION
_AGENTTASK.fields_by_name['explore_machine'].message_type = _EXPLOREWAYPOINT
_AGENTTASK.fields_by_name['workpiece_description'].message_type = _WORKPIECEDESCRIPTION
_AGENTTASK_COMPTYPE.containing_type = _AGENTTASK
_WORKPIECEDESCRIPTION.fields_by_name['base_color'].enum_type = ProductColor__pb2._BASECOLOR
_WORKPIECEDESCRIPTION.fields_by_name['ring_colors'].enum_type = ProductColor__pb2._RINGCOLOR
_WORKPIECEDESCRIPTION.fields_by_name['cap_color'].enum_type = ProductColor__pb2._CAPCOLOR
_WORKPIECEDESCRIPTION_COMPTYPE.containing_type = _WORKPIECEDESCRIPTION
DESCRIPTOR.message_types_by_name['AgentTask'] = _AGENTTASK
DESCRIPTOR.message_types_by_name['Move'] = _MOVE
DESCRIPTOR.message_types_by_name['Retrieve'] = _RETRIEVE
DESCRIPTOR.message_types_by_name['Deliver'] = _DELIVER
DESCRIPTOR.message_types_by_name['BufferStation'] = _BUFFERSTATION
DESCRIPTOR.message_types_by_name['ExploreWaypoint'] = _EXPLOREWAYPOINT
DESCRIPTOR.message_types_by_name['WorkpieceDescription'] = _WORKPIECEDESCRIPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentTask = _reflection.GeneratedProtocolMessageType('AgentTask', (_message.Message,), dict(
  DESCRIPTOR = _AGENTTASK,
  __module__ = 'AgentTask_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.AgentTask)
  ))
_sym_db.RegisterMessage(AgentTask)

Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), dict(
  DESCRIPTOR = _MOVE,
  __module__ = 'AgentTask_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.Move)
  ))
_sym_db.RegisterMessage(Move)

Retrieve = _reflection.GeneratedProtocolMessageType('Retrieve', (_message.Message,), dict(
  DESCRIPTOR = _RETRIEVE,
  __module__ = 'AgentTask_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.Retrieve)
  ))
_sym_db.RegisterMessage(Retrieve)

Deliver = _reflection.GeneratedProtocolMessageType('Deliver', (_message.Message,), dict(
  DESCRIPTOR = _DELIVER,
  __module__ = 'AgentTask_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.Deliver)
  ))
_sym_db.RegisterMessage(Deliver)

BufferStation = _reflection.GeneratedProtocolMessageType('BufferStation', (_message.Message,), dict(
  DESCRIPTOR = _BUFFERSTATION,
  __module__ = 'AgentTask_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.BufferStation)
  ))
_sym_db.RegisterMessage(BufferStation)

ExploreWaypoint = _reflection.GeneratedProtocolMessageType('ExploreWaypoint', (_message.Message,), dict(
  DESCRIPTOR = _EXPLOREWAYPOINT,
  __module__ = 'AgentTask_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.ExploreWaypoint)
  ))
_sym_db.RegisterMessage(ExploreWaypoint)

WorkpieceDescription = _reflection.GeneratedProtocolMessageType('WorkpieceDescription', (_message.Message,), dict(
  DESCRIPTOR = _WORKPIECEDESCRIPTION,
  __module__ = 'AgentTask_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.WorkpieceDescription)
  ))
_sym_db.RegisterMessage(WorkpieceDescription)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
