# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExplorationInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MachineInfo_pb2 as MachineInfo__pb2
import Team_pb2 as Team__pb2
import Zone_pb2 as Zone__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExplorationInfo.proto',
  package='llsf_msgs',
  syntax='proto2',
  serialized_options=_b('\n\037org.robocup_logistics.llsf_msgsB\025ExplorationInfoProtos'),
  serialized_pb=_b('\n\x15\x45xplorationInfo.proto\x12\tllsf_msgs\x1a\x11MachineInfo.proto\x1a\nTeam.proto\x1a\nZone.proto\"o\n\x11\x45xplorationSignal\x12\x0c\n\x04type\x18\x01 \x02(\t\x12$\n\x06lights\x18\x02 \x03(\x0b\x32\x14.llsf_msgs.LightSpec\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x46\"}\n\x0f\x45xplorationZone\x12\x1d\n\x04zone\x18\x02 \x02(\x0e\x32\x0f.llsf_msgs.Zone\x12#\n\nteam_color\x18\x03 \x02(\x0e\x32\x0f.llsf_msgs.Team\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10G\"\x93\x01\n\x0f\x45xplorationInfo\x12-\n\x07signals\x18\x01 \x03(\x0b\x32\x1c.llsf_msgs.ExplorationSignal\x12)\n\x05zones\x18\x02 \x03(\x0b\x32\x1a.llsf_msgs.ExplorationZone\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10HB8\n\x1forg.robocup_logistics.llsf_msgsB\x15\x45xplorationInfoProtos')
  ,
  dependencies=[MachineInfo__pb2.DESCRIPTOR,Team__pb2.DESCRIPTOR,Zone__pb2.DESCRIPTOR,])



_EXPLORATIONSIGNAL_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='llsf_msgs.ExplorationSignal.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=70,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=152,
  serialized_end=190,
)
_sym_db.RegisterEnumDescriptor(_EXPLORATIONSIGNAL_COMPTYPE)

_EXPLORATIONZONE_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='llsf_msgs.ExplorationZone.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=71,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=279,
  serialized_end=317,
)
_sym_db.RegisterEnumDescriptor(_EXPLORATIONZONE_COMPTYPE)

_EXPLORATIONINFO_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='llsf_msgs.ExplorationInfo.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=72,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=429,
  serialized_end=467,
)
_sym_db.RegisterEnumDescriptor(_EXPLORATIONINFO_COMPTYPE)


_EXPLORATIONSIGNAL = _descriptor.Descriptor(
  name='ExplorationSignal',
  full_name='llsf_msgs.ExplorationSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='llsf_msgs.ExplorationSignal.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lights', full_name='llsf_msgs.ExplorationSignal.lights', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXPLORATIONSIGNAL_COMPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=190,
)


_EXPLORATIONZONE = _descriptor.Descriptor(
  name='ExplorationZone',
  full_name='llsf_msgs.ExplorationZone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zone', full_name='llsf_msgs.ExplorationZone.zone', index=0,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=18,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team_color', full_name='llsf_msgs.ExplorationZone.team_color', index=1,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXPLORATIONZONE_COMPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=317,
)


_EXPLORATIONINFO = _descriptor.Descriptor(
  name='ExplorationInfo',
  full_name='llsf_msgs.ExplorationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signals', full_name='llsf_msgs.ExplorationInfo.signals', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zones', full_name='llsf_msgs.ExplorationInfo.zones', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXPLORATIONINFO_COMPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=467,
)

_EXPLORATIONSIGNAL.fields_by_name['lights'].message_type = MachineInfo__pb2._LIGHTSPEC
_EXPLORATIONSIGNAL_COMPTYPE.containing_type = _EXPLORATIONSIGNAL
_EXPLORATIONZONE.fields_by_name['zone'].enum_type = Zone__pb2._ZONE
_EXPLORATIONZONE.fields_by_name['team_color'].enum_type = Team__pb2._TEAM
_EXPLORATIONZONE_COMPTYPE.containing_type = _EXPLORATIONZONE
_EXPLORATIONINFO.fields_by_name['signals'].message_type = _EXPLORATIONSIGNAL
_EXPLORATIONINFO.fields_by_name['zones'].message_type = _EXPLORATIONZONE
_EXPLORATIONINFO_COMPTYPE.containing_type = _EXPLORATIONINFO
DESCRIPTOR.message_types_by_name['ExplorationSignal'] = _EXPLORATIONSIGNAL
DESCRIPTOR.message_types_by_name['ExplorationZone'] = _EXPLORATIONZONE
DESCRIPTOR.message_types_by_name['ExplorationInfo'] = _EXPLORATIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExplorationSignal = _reflection.GeneratedProtocolMessageType('ExplorationSignal', (_message.Message,), dict(
  DESCRIPTOR = _EXPLORATIONSIGNAL,
  __module__ = 'ExplorationInfo_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.ExplorationSignal)
  ))
_sym_db.RegisterMessage(ExplorationSignal)

ExplorationZone = _reflection.GeneratedProtocolMessageType('ExplorationZone', (_message.Message,), dict(
  DESCRIPTOR = _EXPLORATIONZONE,
  __module__ = 'ExplorationInfo_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.ExplorationZone)
  ))
_sym_db.RegisterMessage(ExplorationZone)

ExplorationInfo = _reflection.GeneratedProtocolMessageType('ExplorationInfo', (_message.Message,), dict(
  DESCRIPTOR = _EXPLORATIONINFO,
  __module__ = 'ExplorationInfo_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.ExplorationInfo)
  ))
_sym_db.RegisterMessage(ExplorationInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
