# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrderInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Team_pb2 as Team__pb2
import Time_pb2 as Time__pb2
import ProductColor_pb2 as ProductColor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='OrderInfo.proto',
  package='llsf_msgs',
  syntax='proto2',
  serialized_options=_b('\n\037org.robocup_logistics.llsf_msgsB\017OrderInfoProtos'),
  serialized_pb=_b('\n\x0fOrderInfo.proto\x12\tllsf_msgs\x1a\nTeam.proto\x1a\nTime.proto\x1a\x12ProductColor.proto\"\x90\x01\n\x13UnconfirmedDelivery\x12\n\n\x02id\x18\x01 \x02(\r\x12\x1d\n\x04team\x18\x02 \x02(\x0e\x32\x0f.llsf_msgs.Team\x12&\n\rdelivery_time\x18\x03 \x02(\x0b\x32\x0f.llsf_msgs.Time\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10-\"\xa0\x04\n\x05Order\x12\n\n\x02id\x18\x01 \x02(\r\x12/\n\ncomplexity\x18\x02 \x02(\x0e\x32\x1b.llsf_msgs.Order.Complexity\x12(\n\nbase_color\x18\x03 \x02(\x0e\x32\x14.llsf_msgs.BaseColor\x12)\n\x0bring_colors\x18\x04 \x03(\x0e\x32\x14.llsf_msgs.RingColor\x12&\n\tcap_color\x18\x05 \x02(\x0e\x32\x13.llsf_msgs.CapColor\x12\x1a\n\x12quantity_requested\x18\x06 \x02(\r\x12\x1f\n\x17quantity_delivered_cyan\x18\x07 \x02(\r\x12\"\n\x1aquantity_delivered_magenta\x18\x08 \x02(\r\x12\x1d\n\x15\x64\x65livery_period_begin\x18\t \x02(\r\x12\x1b\n\x13\x64\x65livery_period_end\x18\n \x02(\r\x12\x15\n\rdelivery_gate\x18\x0b \x02(\r\x12>\n\x16unconfirmed_deliveries\x18\x0c \x03(\x0b\x32\x1e.llsf_msgs.UnconfirmedDelivery\x12\x13\n\x0b\x63ompetitive\x18\r \x02(\x08\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10*\",\n\nComplexity\x12\x06\n\x02\x43\x30\x10\x00\x12\x06\n\x02\x43\x31\x10\x01\x12\x06\n\x02\x43\x32\x10\x02\x12\x06\n\x02\x43\x33\x10\x03\"U\n\tOrderInfo\x12 \n\x06orders\x18\x01 \x03(\x0b\x32\x10.llsf_msgs.Order\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10)\"r\n\x11SetOrderDelivered\x12#\n\nteam_color\x18\x01 \x02(\x0e\x32\x0f.llsf_msgs.Team\x12\x10\n\x08order_id\x18\x02 \x02(\r\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10+\"_\n\x0f\x43onfirmDelivery\x12\x13\n\x0b\x64\x65livery_id\x18\x01 \x02(\r\x12\x0f\n\x07\x63orrect\x18\x02 \x02(\x08\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10.B2\n\x1forg.robocup_logistics.llsf_msgsB\x0fOrderInfoProtos')
  ,
  dependencies=[Team__pb2.DESCRIPTOR,Time__pb2.DESCRIPTOR,ProductColor__pb2.DESCRIPTOR,])



_UNCONFIRMEDDELIVERY_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='llsf_msgs.UnconfirmedDelivery.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=45,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=181,
  serialized_end=219,
)
_sym_db.RegisterEnumDescriptor(_UNCONFIRMEDDELIVERY_COMPTYPE)

_ORDER_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='llsf_msgs.Order.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=42,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=682,
  serialized_end=720,
)
_sym_db.RegisterEnumDescriptor(_ORDER_COMPTYPE)

_ORDER_COMPLEXITY = _descriptor.EnumDescriptor(
  name='Complexity',
  full_name='llsf_msgs.Order.Complexity',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='C0', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C1', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C3', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=722,
  serialized_end=766,
)
_sym_db.RegisterEnumDescriptor(_ORDER_COMPLEXITY)

_ORDERINFO_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='llsf_msgs.OrderInfo.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=41,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=815,
  serialized_end=853,
)
_sym_db.RegisterEnumDescriptor(_ORDERINFO_COMPTYPE)

_SETORDERDELIVERED_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='llsf_msgs.SetOrderDelivered.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=43,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=931,
  serialized_end=969,
)
_sym_db.RegisterEnumDescriptor(_SETORDERDELIVERED_COMPTYPE)

_CONFIRMDELIVERY_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='llsf_msgs.ConfirmDelivery.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=46,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1028,
  serialized_end=1066,
)
_sym_db.RegisterEnumDescriptor(_CONFIRMDELIVERY_COMPTYPE)


_UNCONFIRMEDDELIVERY = _descriptor.Descriptor(
  name='UnconfirmedDelivery',
  full_name='llsf_msgs.UnconfirmedDelivery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='llsf_msgs.UnconfirmedDelivery.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team', full_name='llsf_msgs.UnconfirmedDelivery.team', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivery_time', full_name='llsf_msgs.UnconfirmedDelivery.delivery_time', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UNCONFIRMEDDELIVERY_COMPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=219,
)


_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='llsf_msgs.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='llsf_msgs.Order.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='complexity', full_name='llsf_msgs.Order.complexity', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='base_color', full_name='llsf_msgs.Order.base_color', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ring_colors', full_name='llsf_msgs.Order.ring_colors', index=3,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cap_color', full_name='llsf_msgs.Order.cap_color', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity_requested', full_name='llsf_msgs.Order.quantity_requested', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity_delivered_cyan', full_name='llsf_msgs.Order.quantity_delivered_cyan', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity_delivered_magenta', full_name='llsf_msgs.Order.quantity_delivered_magenta', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivery_period_begin', full_name='llsf_msgs.Order.delivery_period_begin', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivery_period_end', full_name='llsf_msgs.Order.delivery_period_end', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivery_gate', full_name='llsf_msgs.Order.delivery_gate', index=10,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unconfirmed_deliveries', full_name='llsf_msgs.Order.unconfirmed_deliveries', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='competitive', full_name='llsf_msgs.Order.competitive', index=12,
      number=13, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ORDER_COMPTYPE,
    _ORDER_COMPLEXITY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=766,
)


_ORDERINFO = _descriptor.Descriptor(
  name='OrderInfo',
  full_name='llsf_msgs.OrderInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orders', full_name='llsf_msgs.OrderInfo.orders', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ORDERINFO_COMPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=768,
  serialized_end=853,
)


_SETORDERDELIVERED = _descriptor.Descriptor(
  name='SetOrderDelivered',
  full_name='llsf_msgs.SetOrderDelivered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_color', full_name='llsf_msgs.SetOrderDelivered.team_color', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order_id', full_name='llsf_msgs.SetOrderDelivered.order_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETORDERDELIVERED_COMPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=855,
  serialized_end=969,
)


_CONFIRMDELIVERY = _descriptor.Descriptor(
  name='ConfirmDelivery',
  full_name='llsf_msgs.ConfirmDelivery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delivery_id', full_name='llsf_msgs.ConfirmDelivery.delivery_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='correct', full_name='llsf_msgs.ConfirmDelivery.correct', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIRMDELIVERY_COMPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=971,
  serialized_end=1066,
)

_UNCONFIRMEDDELIVERY.fields_by_name['team'].enum_type = Team__pb2._TEAM
_UNCONFIRMEDDELIVERY.fields_by_name['delivery_time'].message_type = Time__pb2._TIME
_UNCONFIRMEDDELIVERY_COMPTYPE.containing_type = _UNCONFIRMEDDELIVERY
_ORDER.fields_by_name['complexity'].enum_type = _ORDER_COMPLEXITY
_ORDER.fields_by_name['base_color'].enum_type = ProductColor__pb2._BASECOLOR
_ORDER.fields_by_name['ring_colors'].enum_type = ProductColor__pb2._RINGCOLOR
_ORDER.fields_by_name['cap_color'].enum_type = ProductColor__pb2._CAPCOLOR
_ORDER.fields_by_name['unconfirmed_deliveries'].message_type = _UNCONFIRMEDDELIVERY
_ORDER_COMPTYPE.containing_type = _ORDER
_ORDER_COMPLEXITY.containing_type = _ORDER
_ORDERINFO.fields_by_name['orders'].message_type = _ORDER
_ORDERINFO_COMPTYPE.containing_type = _ORDERINFO
_SETORDERDELIVERED.fields_by_name['team_color'].enum_type = Team__pb2._TEAM
_SETORDERDELIVERED_COMPTYPE.containing_type = _SETORDERDELIVERED
_CONFIRMDELIVERY_COMPTYPE.containing_type = _CONFIRMDELIVERY
DESCRIPTOR.message_types_by_name['UnconfirmedDelivery'] = _UNCONFIRMEDDELIVERY
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['OrderInfo'] = _ORDERINFO
DESCRIPTOR.message_types_by_name['SetOrderDelivered'] = _SETORDERDELIVERED
DESCRIPTOR.message_types_by_name['ConfirmDelivery'] = _CONFIRMDELIVERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnconfirmedDelivery = _reflection.GeneratedProtocolMessageType('UnconfirmedDelivery', (_message.Message,), dict(
  DESCRIPTOR = _UNCONFIRMEDDELIVERY,
  __module__ = 'OrderInfo_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.UnconfirmedDelivery)
  ))
_sym_db.RegisterMessage(UnconfirmedDelivery)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), dict(
  DESCRIPTOR = _ORDER,
  __module__ = 'OrderInfo_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.Order)
  ))
_sym_db.RegisterMessage(Order)

OrderInfo = _reflection.GeneratedProtocolMessageType('OrderInfo', (_message.Message,), dict(
  DESCRIPTOR = _ORDERINFO,
  __module__ = 'OrderInfo_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.OrderInfo)
  ))
_sym_db.RegisterMessage(OrderInfo)

SetOrderDelivered = _reflection.GeneratedProtocolMessageType('SetOrderDelivered', (_message.Message,), dict(
  DESCRIPTOR = _SETORDERDELIVERED,
  __module__ = 'OrderInfo_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.SetOrderDelivered)
  ))
_sym_db.RegisterMessage(SetOrderDelivered)

ConfirmDelivery = _reflection.GeneratedProtocolMessageType('ConfirmDelivery', (_message.Message,), dict(
  DESCRIPTOR = _CONFIRMDELIVERY,
  __module__ = 'OrderInfo_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.ConfirmDelivery)
  ))
_sym_db.RegisterMessage(ConfirmDelivery)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
