# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProductColor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProductColor.proto',
  package='llsf_msgs',
  syntax='proto2',
  serialized_options=_b('\n\037org.robocup_logistics.llsf_msgsB\022ProductColorProtos'),
  serialized_pb=_b('\n\x12ProductColor.proto\x12\tllsf_msgs*L\n\tRingColor\x12\r\n\tRING_BLUE\x10\x01\x12\x0e\n\nRING_GREEN\x10\x02\x12\x0f\n\x0bRING_ORANGE\x10\x03\x12\x0f\n\x0bRING_YELLOW\x10\x04*J\n\tBaseColor\x12\x0c\n\x08\x42\x41SE_RED\x10\x01\x12\x0e\n\nBASE_BLACK\x10\x02\x12\x0f\n\x0b\x42\x41SE_SILVER\x10\x03\x12\x0e\n\nBASE_CLEAR\x10\x04*\'\n\x08\x43\x61pColor\x12\r\n\tCAP_BLACK\x10\x01\x12\x0c\n\x08\x43\x41P_GREY\x10\x02\x42\x35\n\x1forg.robocup_logistics.llsf_msgsB\x12ProductColorProtos')
)

_RINGCOLOR = _descriptor.EnumDescriptor(
  name='RingColor',
  full_name='llsf_msgs.RingColor',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RING_BLUE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RING_GREEN', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RING_ORANGE', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RING_YELLOW', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=33,
  serialized_end=109,
)
_sym_db.RegisterEnumDescriptor(_RINGCOLOR)

RingColor = enum_type_wrapper.EnumTypeWrapper(_RINGCOLOR)
_BASECOLOR = _descriptor.EnumDescriptor(
  name='BaseColor',
  full_name='llsf_msgs.BaseColor',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BASE_RED', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASE_BLACK', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASE_SILVER', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BASE_CLEAR', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=111,
  serialized_end=185,
)
_sym_db.RegisterEnumDescriptor(_BASECOLOR)

BaseColor = enum_type_wrapper.EnumTypeWrapper(_BASECOLOR)
_CAPCOLOR = _descriptor.EnumDescriptor(
  name='CapColor',
  full_name='llsf_msgs.CapColor',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CAP_BLACK', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAP_GREY', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=187,
  serialized_end=226,
)
_sym_db.RegisterEnumDescriptor(_CAPCOLOR)

CapColor = enum_type_wrapper.EnumTypeWrapper(_CAPCOLOR)
RING_BLUE = 1
RING_GREEN = 2
RING_ORANGE = 3
RING_YELLOW = 4
BASE_RED = 1
BASE_BLACK = 2
BASE_SILVER = 3
BASE_CLEAR = 4
CAP_BLACK = 1
CAP_GREY = 2


DESCRIPTOR.enum_types_by_name['RingColor'] = _RINGCOLOR
DESCRIPTOR.enum_types_by_name['BaseColor'] = _BASECOLOR
DESCRIPTOR.enum_types_by_name['CapColor'] = _CAPCOLOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
