# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Time.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Time.proto',
  package='llsf_msgs',
  syntax='proto2',
  serialized_options=_b('\n\037org.robocup_logistics.llsf_msgsB\nTimeProtos'),
  serialized_pb=_b('\n\nTime.proto\x12\tllsf_msgs\"!\n\x04Time\x12\x0b\n\x03sec\x18\x01 \x02(\x03\x12\x0c\n\x04nsec\x18\x02 \x02(\x03\x42-\n\x1forg.robocup_logistics.llsf_msgsB\nTimeProtos')
)




_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='llsf_msgs.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sec', full_name='llsf_msgs.Time.sec', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nsec', full_name='llsf_msgs.Time.nsec', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['Time'] = _TIME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), dict(
  DESCRIPTOR = _TIME,
  __module__ = 'Time_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.Time)
  ))
_sym_db.RegisterMessage(Time)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
