# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VersionInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VersionInfo.proto',
  package='llsf_msgs',
  syntax='proto2',
  serialized_options=_b('\n\037org.robocup_logistics.llsf_msgsB\rVersionProtos'),
  serialized_pb=_b('\n\x11VersionInfo.proto\x12\tllsf_msgs\"\x92\x01\n\x0bVersionInfo\x12\x15\n\rversion_major\x18\x01 \x02(\r\x12\x15\n\rversion_minor\x18\x02 \x02(\r\x12\x15\n\rversion_micro\x18\x03 \x02(\r\x12\x16\n\x0eversion_string\x18\x04 \x02(\t\"&\n\x08\x43ompType\x12\x0c\n\x07\x43OMP_ID\x10\xd0\x0f\x12\x0c\n\x08MSG_TYPE\x10\x03\x42\x30\n\x1forg.robocup_logistics.llsf_msgsB\rVersionProtos')
)



_VERSIONINFO_COMPTYPE = _descriptor.EnumDescriptor(
  name='CompType',
  full_name='llsf_msgs.VersionInfo.CompType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMP_ID', index=0, number=2000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE', index=1, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=141,
  serialized_end=179,
)
_sym_db.RegisterEnumDescriptor(_VERSIONINFO_COMPTYPE)


_VERSIONINFO = _descriptor.Descriptor(
  name='VersionInfo',
  full_name='llsf_msgs.VersionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version_major', full_name='llsf_msgs.VersionInfo.version_major', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version_minor', full_name='llsf_msgs.VersionInfo.version_minor', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version_micro', full_name='llsf_msgs.VersionInfo.version_micro', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version_string', full_name='llsf_msgs.VersionInfo.version_string', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VERSIONINFO_COMPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=179,
)

_VERSIONINFO_COMPTYPE.containing_type = _VERSIONINFO
DESCRIPTOR.message_types_by_name['VersionInfo'] = _VERSIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionInfo = _reflection.GeneratedProtocolMessageType('VersionInfo', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONINFO,
  __module__ = 'VersionInfo_pb2'
  # @@protoc_insertion_point(class_scope:llsf_msgs.VersionInfo)
  ))
_sym_db.RegisterMessage(VersionInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
