// Generated by gencpp from file simulator/FindObject.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_FINDOBJECT_H
#define SIMULATOR_MESSAGE_FINDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct FindObject_
{
  typedef FindObject_<ContainerAllocator> Type;

  FindObject_()
    : stamp()
    , data(0)
    , find()  {
    }
  FindObject_(const ContainerAllocator& _alloc)
    : stamp()
    , data(0)
    , find(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef int32_t _data_type;
  _data_type data;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _find_type;
  _find_type find;





  typedef boost::shared_ptr< ::simulator::FindObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::FindObject_<ContainerAllocator> const> ConstPtr;

}; // struct FindObject_

typedef ::simulator::FindObject_<std::allocator<void> > FindObject;

typedef boost::shared_ptr< ::simulator::FindObject > FindObjectPtr;
typedef boost::shared_ptr< ::simulator::FindObject const> FindObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::FindObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::FindObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simulator::FindObject_<ContainerAllocator1> & lhs, const ::simulator::FindObject_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.data == rhs.data &&
    lhs.find == rhs.find;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simulator::FindObject_<ContainerAllocator1> & lhs, const ::simulator::FindObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simulator::FindObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::FindObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::FindObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::FindObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::FindObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::FindObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::FindObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb15142359af0b90fb9cb56381869bdd";
  }

  static const char* value(const ::simulator::FindObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb15142359af0b90ULL;
  static const uint64_t static_value2 = 0xfb9cb56381869bddULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::FindObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/FindObject";
  }

  static const char* value(const ::simulator::FindObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::FindObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"int32 data\n"
"string find\n"
;
  }

  static const char* value(const ::simulator::FindObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::FindObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.data);
      stream.next(m.find);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::FindObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::FindObject_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "find: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.find);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_FINDOBJECT_H
