// Generated by gencpp from file simulator/QueryKDBResponse.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_QUERYKDBRESPONSE_H
#define SIMULATOR_MESSAGE_QUERYKDBRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct QueryKDBResponse_
{
  typedef QueryKDBResponse_<ContainerAllocator> Type;

  QueryKDBResponse_()
    : result()  {
    }
  QueryKDBResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::simulator::QueryKDBResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::QueryKDBResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QueryKDBResponse_

typedef ::simulator::QueryKDBResponse_<std::allocator<void> > QueryKDBResponse;

typedef boost::shared_ptr< ::simulator::QueryKDBResponse > QueryKDBResponsePtr;
typedef boost::shared_ptr< ::simulator::QueryKDBResponse const> QueryKDBResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::QueryKDBResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::QueryKDBResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simulator::QueryKDBResponse_<ContainerAllocator1> & lhs, const ::simulator::QueryKDBResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simulator::QueryKDBResponse_<ContainerAllocator1> & lhs, const ::simulator::QueryKDBResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simulator::QueryKDBResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::QueryKDBResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::QueryKDBResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::QueryKDBResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::QueryKDBResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::QueryKDBResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::QueryKDBResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::simulator::QueryKDBResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::QueryKDBResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/QueryKDBResponse";
  }

  static const char* value(const ::simulator::QueryKDBResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::QueryKDBResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::simulator::QueryKDBResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::QueryKDBResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryKDBResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::QueryKDBResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::QueryKDBResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_QUERYKDBRESPONSE_H
