// Generated by gencpp from file simulator/simulator_algorithm_resultResponse.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_ALGORITHM_RESULTRESPONSE_H
#define SIMULATOR_MESSAGE_SIMULATOR_ALGORITHM_RESULTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_algorithm_resultResponse_
{
  typedef simulator_algorithm_resultResponse_<ContainerAllocator> Type;

  simulator_algorithm_resultResponse_()
    : success(0)  {
    }
  simulator_algorithm_resultResponse_(const ContainerAllocator& _alloc)
    : success(0)  {
  (void)_alloc;
    }



   typedef int32_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_algorithm_resultResponse_

typedef ::simulator::simulator_algorithm_resultResponse_<std::allocator<void> > simulator_algorithm_resultResponse;

typedef boost::shared_ptr< ::simulator::simulator_algorithm_resultResponse > simulator_algorithm_resultResponsePtr;
typedef boost::shared_ptr< ::simulator::simulator_algorithm_resultResponse const> simulator_algorithm_resultResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator1> & lhs, const ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator1> & lhs, const ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c2bcf2ff0894cb3058b1bf4c8c4175a";
  }

  static const char* value(const ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c2bcf2ff0894cb3ULL;
  static const uint64_t static_value2 = 0x058b1bf4c8c4175aULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_algorithm_resultResponse";
  }

  static const char* value(const ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 success\n"
;
  }

  static const char* value(const ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_algorithm_resultResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_algorithm_resultResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<int32_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_ALGORITHM_RESULTRESPONSE_H
