// Generated by gencpp from file simulator/simulator_action_planner.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_ACTION_PLANNER_H
#define SIMULATOR_MESSAGE_SIMULATOR_ACTION_PLANNER_H

#include <ros/service_traits.h>


#include <simulator/simulator_action_plannerRequest.h>
#include <simulator/simulator_action_plannerResponse.h>


namespace simulator
{

struct simulator_action_planner
{

typedef simulator_action_plannerRequest Request;
typedef simulator_action_plannerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simulator_action_planner
} // namespace simulator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulator::simulator_action_planner > {
  static const char* value()
  {
    return "5d4b465f13d9abdf0754aeb1704ce89b";
  }

  static const char* value(const ::simulator::simulator_action_planner&) { return value(); }
};

template<>
struct DataType< ::simulator::simulator_action_planner > {
  static const char* value()
  {
    return "simulator/simulator_action_planner";
  }

  static const char* value(const ::simulator::simulator_action_planner&) { return value(); }
};


// service_traits::MD5Sum< ::simulator::simulator_action_plannerRequest> should match
// service_traits::MD5Sum< ::simulator::simulator_action_planner >
template<>
struct MD5Sum< ::simulator::simulator_action_plannerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_action_planner >::value();
  }
  static const char* value(const ::simulator::simulator_action_plannerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_action_plannerRequest> should match
// service_traits::DataType< ::simulator::simulator_action_planner >
template<>
struct DataType< ::simulator::simulator_action_plannerRequest>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_action_planner >::value();
  }
  static const char* value(const ::simulator::simulator_action_plannerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulator::simulator_action_plannerResponse> should match
// service_traits::MD5Sum< ::simulator::simulator_action_planner >
template<>
struct MD5Sum< ::simulator::simulator_action_plannerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_action_planner >::value();
  }
  static const char* value(const ::simulator::simulator_action_plannerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_action_plannerResponse> should match
// service_traits::DataType< ::simulator::simulator_action_planner >
template<>
struct DataType< ::simulator::simulator_action_plannerResponse>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_action_planner >::value();
  }
  static const char* value(const ::simulator::simulator_action_plannerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_ACTION_PLANNER_H
