// Generated by gencpp from file simulator/simulator_MoveRealRobotRequest.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_MOVEREALROBOTREQUEST_H
#define SIMULATOR_MESSAGE_SIMULATOR_MOVEREALROBOTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_MoveRealRobotRequest_
{
  typedef simulator_MoveRealRobotRequest_<ContainerAllocator> Type;

  simulator_MoveRealRobotRequest_()
    : theta(0.0)
    , distance(0.0)  {
    }
  simulator_MoveRealRobotRequest_(const ContainerAllocator& _alloc)
    : theta(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef float _theta_type;
  _theta_type theta;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_MoveRealRobotRequest_

typedef ::simulator::simulator_MoveRealRobotRequest_<std::allocator<void> > simulator_MoveRealRobotRequest;

typedef boost::shared_ptr< ::simulator::simulator_MoveRealRobotRequest > simulator_MoveRealRobotRequestPtr;
typedef boost::shared_ptr< ::simulator::simulator_MoveRealRobotRequest const> simulator_MoveRealRobotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator1> & lhs, const ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator2> & rhs)
{
  return lhs.theta == rhs.theta &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator1> & lhs, const ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "428ccb9659c7d3f0c6c3a803af59d6ab";
  }

  static const char* value(const ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x428ccb9659c7d3f0ULL;
  static const uint64_t static_value2 = 0xc6c3a803af59d6abULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_MoveRealRobotRequest";
  }

  static const char* value(const ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 theta\n"
"float32 distance\n"
;
  }

  static const char* value(const ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_MoveRealRobotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_MoveRealRobotRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_MOVEREALROBOTREQUEST_H
