// Generated by gencpp from file simulator/simulator_laserRequest.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_LASERREQUEST_H
#define SIMULATOR_MESSAGE_SIMULATOR_LASERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_laserRequest_
{
  typedef simulator_laserRequest_<ContainerAllocator> Type;

  simulator_laserRequest_()
    : robot_x(0.0)
    , robot_y(0.0)
    , robot_theta(0.0)
    , new_simulation(0)  {
    }
  simulator_laserRequest_(const ContainerAllocator& _alloc)
    : robot_x(0.0)
    , robot_y(0.0)
    , robot_theta(0.0)
    , new_simulation(0)  {
  (void)_alloc;
    }



   typedef float _robot_x_type;
  _robot_x_type robot_x;

   typedef float _robot_y_type;
  _robot_y_type robot_y;

   typedef float _robot_theta_type;
  _robot_theta_type robot_theta;

   typedef int32_t _new_simulation_type;
  _new_simulation_type new_simulation;





  typedef boost::shared_ptr< ::simulator::simulator_laserRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_laserRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_laserRequest_

typedef ::simulator::simulator_laserRequest_<std::allocator<void> > simulator_laserRequest;

typedef boost::shared_ptr< ::simulator::simulator_laserRequest > simulator_laserRequestPtr;
typedef boost::shared_ptr< ::simulator::simulator_laserRequest const> simulator_laserRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_laserRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_laserRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simulator::simulator_laserRequest_<ContainerAllocator1> & lhs, const ::simulator::simulator_laserRequest_<ContainerAllocator2> & rhs)
{
  return lhs.robot_x == rhs.robot_x &&
    lhs.robot_y == rhs.robot_y &&
    lhs.robot_theta == rhs.robot_theta &&
    lhs.new_simulation == rhs.new_simulation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simulator::simulator_laserRequest_<ContainerAllocator1> & lhs, const ::simulator::simulator_laserRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_laserRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_laserRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_laserRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_laserRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_laserRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_laserRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_laserRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9121e8f7eca3a126128d3865e9b6a1c";
  }

  static const char* value(const ::simulator::simulator_laserRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9121e8f7eca3a12ULL;
  static const uint64_t static_value2 = 0x6128d3865e9b6a1cULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_laserRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_laserRequest";
  }

  static const char* value(const ::simulator::simulator_laserRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_laserRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 robot_x\n"
"float32 robot_y\n"
"float32 robot_theta\n"
"int32 new_simulation\n"
;
  }

  static const char* value(const ::simulator::simulator_laserRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_laserRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_x);
      stream.next(m.robot_y);
      stream.next(m.robot_theta);
      stream.next(m.new_simulation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_laserRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_laserRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_laserRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "robot_x: ";
    Printer<float>::stream(s, indent + "  ", v.robot_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "robot_y: ";
    Printer<float>::stream(s, indent + "  ", v.robot_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "robot_theta: ";
    Printer<float>::stream(s, indent + "  ", v.robot_theta);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "new_simulation: ";
    Printer<int32_t>::stream(s, indent + "  ", v.new_simulation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_LASERREQUEST_H
