// Generated by gencpp from file simulator/simulator_manipulator.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_MANIPULATOR_H
#define SIMULATOR_MESSAGE_SIMULATOR_MANIPULATOR_H

#include <ros/service_traits.h>


#include <simulator/simulator_manipulatorRequest.h>
#include <simulator/simulator_manipulatorResponse.h>


namespace simulator
{

struct simulator_manipulator
{

typedef simulator_manipulatorRequest Request;
typedef simulator_manipulatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simulator_manipulator
} // namespace simulator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulator::simulator_manipulator > {
  static const char* value()
  {
    return "79bc46f7abed5f24dda02ac0e109caf4";
  }

  static const char* value(const ::simulator::simulator_manipulator&) { return value(); }
};

template<>
struct DataType< ::simulator::simulator_manipulator > {
  static const char* value()
  {
    return "simulator/simulator_manipulator";
  }

  static const char* value(const ::simulator::simulator_manipulator&) { return value(); }
};


// service_traits::MD5Sum< ::simulator::simulator_manipulatorRequest> should match
// service_traits::MD5Sum< ::simulator::simulator_manipulator >
template<>
struct MD5Sum< ::simulator::simulator_manipulatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_manipulator >::value();
  }
  static const char* value(const ::simulator::simulator_manipulatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_manipulatorRequest> should match
// service_traits::DataType< ::simulator::simulator_manipulator >
template<>
struct DataType< ::simulator::simulator_manipulatorRequest>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_manipulator >::value();
  }
  static const char* value(const ::simulator::simulator_manipulatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulator::simulator_manipulatorResponse> should match
// service_traits::MD5Sum< ::simulator::simulator_manipulator >
template<>
struct MD5Sum< ::simulator::simulator_manipulatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_manipulator >::value();
  }
  static const char* value(const ::simulator::simulator_manipulatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_manipulatorResponse> should match
// service_traits::DataType< ::simulator::simulator_manipulator >
template<>
struct DataType< ::simulator::simulator_manipulatorResponse>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_manipulator >::value();
  }
  static const char* value(const ::simulator::simulator_manipulatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_MANIPULATOR_H
